name: Functional Test Linux
on: [ push ]
jobs:
  test:
    name: Functional Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Dependencies
        shell: bash
        run: |
          set -e
          cat /etc/os-release 
          sudo apt-get update >/dev/null
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq ncat
          curl -LOs "https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz"
          tar xf shellcheck-v0.8.0.linux.x86_64.tar.xz shellcheck-v0.8.0/shellcheck
          mv shellcheck-v0.8.0/shellcheck /usr/local/bin/
          shellcheck -V

      - name: Run pairing service
        shell: bash
        run: bash .github/scripts/run_pairing_service.sh

      - name: Run RPort Server
        shell: bash
        run: bash .github/scripts/run_rport_server.sh

      - name: Functional Linux Test & Shell Script Lint
        shell: bash
        run: bash .github/scripts/functional_test.sh