name: Test
on: [ push ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test
        run: go test -race ./...

      - name: Functional Test
        shell: bash
        run: |
          set -e
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq
          bash .github/scripts/functional_test.sh