name: Test
on: [ push ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test
        run: go test -race ./...

      - name: Install Dependencies
        shell: bash
        run: |
          set -e
          sudo apt-get update >/dev/null
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq

      - name: Functional Test
        shell: bash
        run: |
          set -e
          pwd
          ls -la
          bash -x .github/scripts/functional_test.sh